services:
  evrinoma.advantage.constraint.property.name:
    class: Evrinoma\AdvantageBundle\Constraint\Property\Name

  evrinoma.advantage.constraint.property.url:
    class: Evrinoma\AdvantageBundle\Constraint\Property\Url

  evrinoma.advantage.constraint.property.active:
    class: Evrinoma\AdvantageBundle\Constraint\Property\Active
